GET http://localhost:3000/posts 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMxMTkyMjYzfQ.XZir8t2sAvtZeSR-GLquiepuMBLDVthBlZoS-P8vgiw

###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMxMTkyMTgwLCJleHAiOjE2MzExOTIxOTV9.VKYvk08mNIjQejnbBq2WLPUCAx-VO5D0KwMvkqZWoDk"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMxMTkyMjI2LCJleHAiOjE2MzExOTIyNDF9.xn3kuEpQ5ZTJYkmPwISvVkYn8OttV5K_lfWt4UOJcPU"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
"username": "Jim"
}

