GET http://localhost:3000/posts 
Authorization: Bearer 
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMxMDgxODYxLCJleHAiOjE2MzEwODE4NzZ9.oPIEYG1h6qGW6ZB30y2BIuoOOIzZ_aupCicYbgB63GE

###

DELETE http://localhost:4000/logout 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMxMDgxNzkxLCJleHAiOjE2MzEwODE4MDZ9.RqidtFCHOTdCbY_XCOlGZXGGEhfkhUdDIA-pG7y8tjY"
}

###

POST http://localhost:4000/token 
Content-Type: application/json

{
"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjMxMDgxODQyfQ.jcuCu6es8FlQoZLi9ElTjRPfZw8d9DJBeblDPX-R0Pg"
}

###

POST http://localhost:4000/login 
Content-Type: application/json

{
"username": "Jim"
}

